### ISSUE TITLE
Spruce up terminal messages

### ISSUE THREAD

**Issue by Slackadays** [sudofox/weight#1]
I like this script, but I feel like it's a little plain. I'm too used to the colorful nature of Clipboard so I was wondering if it would be possible to add some color codes to the messages so it looks more interesting and "official." I don't know what colors would be the best, so you can choose (or I can if you can't either)

**Comment by sudofox** [comment]
I'm not sure I agree that it needs anything else; while I am a sucker for terminal color codes, I take some pride in the simplicity of this particular project.
Give me your best mspaint/gimp mockup and i'll think about it

**Comment by Slackadays** [comment]
I didn't actually need to make a GIMP/MSPaint mockup, because you can do this in the terminal :)

Here's what I got with this:
```bash
echo -e "\033[92mUsage: $0 <weight in lbs>\033[0m"
echo -e "\033[36mWeight already entered for today :)\033[0m"
echo -e "\033[92mCurrent weight: $LW_POUNDS lbs ($LW_KILOGRAMS kg) measured on $LW_DATE ($LW_DELTA_PLUS_OR_MINUS$LW_DELTA_POUNDS lbs/$LW_DELTA_KILOGRAMS kg)\033[0m"
```

![image](https://user-images.githubusercontent.com/69403549/213831476-172cd89e-aaa3-482b-a9a3-b8cc8b3833e1.png)

**Comment by sudofox** [comment]
There you go
